# Ansible 判断和循环
## 标准循环 
- name: add several users 
  user: name={{ item }} state=present groups=wheel 
  with_items: 
    - testuser1 
    - testuser2 
  password: pa={{ item }} 
  with_items:
    {{ pack }}

# 字典循环 
- name: add several users 
  user: name={{ item.name }} state=present groups={{ item.groups }} 
  with_items:
    - { name: 'testuser1', groups: 'wheel' }
    - { name: 'testuser2', groups: 'root' }


# 嵌套循环 
- name: test  
  hosts: masters 
  tasks: 
    - name: give users access to multiple databases 
      command: "echo name={{ item[0] }} priv={{ item[1] }} test={{ item[2] }}" 
      with_nested: 
        - [ 'alice', 'bob' ] 
        - [ 'clientdb', 'employeedb', 'providerdb' ] 
        - ['1', '2' ]

# 字典循环 
users: 
  alice: 
    name: Alice Appleworth 
    telephone: 123-456-7890
  bob: 
    name: bob bannaram 
    telephone: 987
tasks: 
  - name: print phone records 
    debug: msg="User {{ item.key }} is {{ item.value.name }} ({{ item.value.telephone }})"
    with_dict:
      "{{ users }}"

# 文件循环
with_file是将每个文件的内容作为item的值 
with_fileglob是将每个文件的全路径作为item的值，在文件目录下是非递归的。 
- copy: src={{ item }} dest=/etc/fooapp/ owner=root mode=600 
  with_fileglob:
    - /playbooks/files/fooapp/*  

#with_together 
tasks: 
  - command: echo "msg={{ item.0 }} and {{ item.1 }}" 
    with_together: 
      - [ 1, 2, 3 ]
      - [ 4, 5 ]
