#!/bin/bash

get_memory_usage()
{
	total_memory=`free -m | grep Mem | awk '{print $2}'`
	used_memory=`free -m | grep Mem | awk '{print $3}'`
	echo "total memory: $total_memory"
	echo "used memory: $used_memory"
}

get_swap_usage()
{
	total_swap=`free -m | grep Swap | awk '{print $2}'`
	if [ -z $total_swap ];then
		echo "---no swap, add one recommended---"
	else
		used_swap=` free -m | grep Swap | awk '{print $3}'`
		echo "Swap Used: $used_swap"
	fi
}

memory()
{
	get_memory_usage
	get_swap_usage
}
