#!/bin/bash

network_state()
{
	network_dev=`cat /proc/net/dev | sed '1,2d' | awk -F ":" '{print $1}' | sed '/lo/d'`
	for dev in $network_dev
	do
		speed=`ethtool $dev | grep speed:`
		echo "speed of $dev: $speed"
	done
	echo
}
