#!/bin/bash

system_process()
{
  echo "Process/Threads: "`ps -elf | wc -l`/`ps -eLf | wc -l` 
  echo "Zombies: "`ps -ef | grep defunct | grep -v grep | wc -l`
  echo "D process: "`ps -A -ostat,ppid,pid,cmd | grep -E '^[dD]' | wc -l`
  echo
}

